const BETTER_AUTH_SECRET = process.env.BETTER_AUTH_SECRET;
const BETTER_AUTH_URL = process.env.BETTER_AUTH_URL;
const GOOGLE_AUTH_CLIENT_SECRET = process.env.GOOGLE_AUTH_CLIENT_SECRET;
const GOOGLE_AUTH_CLIENT_ID = process.env.GOOGLE_AUTH_CLIENT_ID;
const DATABASE_URL = process.env.DATABASE_URL;

export {
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL,
  GOOGLE_AUTH_CLIENT_SECRET,
  GOOGLE_AUTH_CLIENT_ID,
  DATABASE_URL,
};
